spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.100.75:1521:xe
    username: dev01
    password: 1234
#  web:
#    resources:
#      static-locations: classpath:/templates/, classpath:/static/
#  servlet:
#    multipart:
#      max-request-size: 10MB
#      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: intj.project.boot.entity, intj.project.boot.dto
  configuration:
    map-underscore-to-camel-case: true